In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
A = np.random.randn(10)

A

array([-0.02559069, -0.90355961,  0.50161587,  2.1453087 , -3.24275395,
       -0.25921354, -0.19977367,  0.53800336, -0.73987833,  0.42611281])

In [9]:
B = np.random.randn(10)

B

array([ 2.16786743, -0.42547212,  1.56269093, -0.27753465, -0.48429073,
        0.66803296, -1.75802126, -0.62532065, -0.17099364, -0.61667923])

In [10]:
#Binary Functions

np.add(A, B)

array([ 2.14227674, -1.32903173,  2.0643068 ,  1.86777404, -3.72704468,
        0.40881942, -1.95779493, -0.08731729, -0.91087198, -0.19056642])

In [11]:
np.maximum(A, B)

array([ 2.16786743, -0.42547212,  1.56269093,  2.1453087 , -0.48429073,
        0.66803296, -0.19977367,  0.53800336, -0.17099364,  0.42611281])

In [12]:
np.minimum(A, B)

array([-0.02559069, -0.90355961,  0.50161587, -0.27753465, -3.24275395,
       -0.25921354, -1.75802126, -0.62532065, -0.73987833, -0.61667923])

In [15]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True